# Generated by Django 5.1 on 2025-03-29 08:53

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='user_fhKsrx', editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='ven_DF4k7v', editable=False, max_length=22, unique=True),
        ),
    ]
