# Generated by Django 5.1 on 2025-04-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_userprofile_uid_alter_vendorprofile_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='country',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Vendor', 'Vendor'), ('Admin', 'Admin')], default='User', max_length=10),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
