# Generated by Django 5.1 on 2025-04-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_account_groups_account_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='user',
            new_name='VendorProfile',
        ),
    ]
