# Generated by Django 5.1 on 2025-03-29 08:53

import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('Nháp', 'Nháp'), ('Từ chối', 'Từ chối'), ('Ok', 'Ok'), ('Đang duyệt', 'Đang duyệt'), ('Hủy', 'Hủy')], default='Ok', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='sku_YKE965', editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.tag'),
        ),
    ]
