# Generated by Django 5.1 on 2025-03-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
