# Generated by Django 5.1 on 2025-03-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_variation_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='quantity',
        ),
    ]
