# Generated by Django 5.1 on 2025-04-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_category_vendor'),
        ('Store', '0007_remove_product_user_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='categoryProduct', to='Category.category'),
        ),
    ]
