# Generated by Django 5.1 on 2025-02-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture_profile',
            field=models.ImageField(upload_to='user/avt'),
        ),
    ]
