# Generated by Django 5.1 on 2025-03-30 08:35

import shortuuidfield.fields
import utils.python.uid
import utils.python.vid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_userprofile_uid_alter_vendorprofile_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=utils.python.uid.generate_uid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=utils.python.vid.generate_vid, editable=False, max_length=22, unique=True),
        ),
    ]
