# Generated by Django 5.1 on 2025-04-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_userprofile_address_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='warranty_period',
            field=models.CharField(default='100', max_length=100),
        ),
    ]
