# Generated by Django 5.1 on 2025-05-03 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_userprofile_user'),
        ('Store', '0002_remove_reviewrating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile'),
        ),
    ]
