# Generated by Django 5.1 on 2025-04-30 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('Store', '0002_product_specification_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='create_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewRating', to='Account.userprofile'),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productReview', to='Store.product'),
        ),
    ]
