# Generated by Django 5.1 on 2025-03-29 08:58

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_product_image_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='sku_Y4VXFt', editable=False, max_length=22, unique=True),
        ),
    ]
