# Generated by Django 5.1 on 2025-03-30 08:35

import shortuuidfield.fields
import utils.python.sku
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=utils.python.sku.generate_sku, editable=False, max_length=22, unique=True),
        ),
    ]
