# Generated by Django 5.1 on 2025-03-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0001_initial'),
        ('Store', '0005_remove_variation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='Store.variation'),
        ),
    ]
